MAP = [
    'wwwwwwwwwwwwwwwwwww',
    'wp                w',
    'w                 w',
    'w                 w',
    'w                 w',
    'w                 w',
    'w                 w',
    'w                 w',
    'w                 w',
    'w                 w',
    'wwwwwwwwwwwwwwwwwww',
]
MAP2 = ['wwwwwwwwwwwwwwwwwww',
        'wp                w',
        'w                 w',
        'w                 w',
        'w                 w',
        'w                 w',
        'w                 w',
        'w                 w',
        'w                 w',
        'w                 w',
        'wwwwwwwwwwwwwwwwwww',]